<?php if(Mage::getStoreConfig('chandancomment/comment_group/comment_status',Mage::app()->getStore())) { ?>
<div class="tunki">
	<h4><?php echo $this->__('Delivery Date') ?></h4>
	<input type="date" name="ordercomment" id="ordercomment"/>
	<input type="time" name="test" id="test"/>	
</div>

<script type="text/javascript">    
	jQuery(document).ready(function()
	{
		var p_tunki,test;
		jQuery("#ordercomment").blur(function(){
			p_tunki = jQuery("#ordercomment").val();		
		});
		jQuery("#test").blur(function(){
			test = jQuery("#test").val();		
			jQuery.ajax({
				type : "post",
				url : "<?php echo $this->getUrl();?>comment/index/textval",
				data : {ordercomment:p_tunki,test:test},
				success: function(text){
				//	alert('hi');
				}
			});
		});
	});
</script>
<?php } ?>
