
<div class="entry-edit box-left">
    <div class="entry-edit-head">
        <h4 class="icon-head"><?php echo $this->__('Delivery Date') ?></h4>
    </div>
    <fieldset>
        <div id="mymodule_custom_block">
            <?php $order = $this->getOrder(); 
			$connection = Mage::getSingleton('core/resource')->getConnection('core_read');
			$sql        = "SELECT comment FROM comment where ordernumber= ".$order->getIncrementId()."";
			$rows       = $connection->fetchcol($sql); 
			echo "<b>Delivery Date is :-".$rows[0]."</b>";
            ?>
        </div>
    </fieldset>
</div>
<div class="clear"></div>